name: PR Open to Master Workflows
on:
  pull_request:
    types: [opened]
    branches:
      - master

jobs:
  postman-test-run:
    name: "Postman Regression Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}
          ref: develop

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Regression
        run: |
          npm install
          npm run-script postmanDevelop

      - name: Commit Report
        run: |
          git config --global user.name 'furknyavuz'
          git config --global user.email 'furknyavuz@gmail.com'
          git add .
          git commit -m "Automated report"
          git push

      - name: Output the Run Details
        uses: actions/upload-artifact@v2
        with:
          name: PostmanReports
          path: ./assets/test-results
